# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d524effc772153e03e122ebdfacdb92f16c4e8a559d63de7eae8590d9faf119283743b61880f36da2a1c6fda1ebbb1e2b73162514f7283faff16741670ccde

test:
  secret_key_base: d3be8515b436c54df979c8d600caf0cda983ba34d359d7658e853e96c8ba94f2baf040c0d21b91a95b823a7cb109b020a21020dc71b87eb848dac5de833b3f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
